using System.IO;

namespace WpfDesktop.Services;

/// <summary>
/// 扩展模型路径 YAML 内容生成辅助类。
/// </summary>
public static class ExtraModelPathsYamlHelper
{
    /// <summary>
    /// 根据基础目录生成 extra_model_paths.yaml 文件内容。
    /// </summary>
    /// <param name="basePath">模型基础目录。</param>
    /// <returns>符合 ComfyUI 格式的 YAML 文本。</returns>
    public static string GenerateYamlContent(string basePath)
    {
        var normalizedPath = basePath.Replace('\\', '/');
        if (!normalizedPath.EndsWith('/'))
        {
            normalizedPath += '/';
        }

        var hasModelsSubdir = Directory.Exists(Path.Combine(basePath, "models"));
        var hasDirectModelDirs =
            Directory.Exists(Path.Combine(basePath, "checkpoints")) ||
            Directory.Exists(Path.Combine(basePath, "loras")) ||
            Directory.Exists(Path.Combine(basePath, "vae")) ||
            Directory.Exists(Path.Combine(basePath, "clip"));

        var modelPrefix = hasDirectModelDirs && !hasModelsSubdir ? string.Empty : "models/";
        var modelsRoot = modelPrefix.Length == 0 ? basePath : Path.Combine(basePath, "models");

        var pathEntries = new List<(string Key, string RelativePath)>();
        if (Directory.Exists(modelsRoot))
        {
            foreach (var dir in Directory.EnumerateDirectories(modelsRoot))
            {
                var dirName = Path.GetFileName(dir);
                if (string.IsNullOrWhiteSpace(dirName))
                {
                    continue;
                }

                var relativePath = $"{modelPrefix}{dirName}/".Replace('\\', '/');
                pathEntries.Add((dirName, relativePath));
            }
        }

        pathEntries = pathEntries
            .OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var yamlLines = new List<string>
        {
            "# Auto-generated by ComfyShell",
            "# 扩展模型路径配置",
            "",
            "comfyui_extra:",
            $"    base_path: {normalizedPath}"
        };

        foreach (var (key, relativePath) in pathEntries)
        {
            yamlLines.Add($"    {key}: {relativePath}");
        }

        yamlLines.Add(string.Empty);
        return string.Join(Environment.NewLine, yamlLines);
    }
}
