using System.IO;

namespace WpfDesktop.Services;

/// <summary>
/// 扩展模型路径 YAML 内容生成辅助类。
/// </summary>
public static class ExtraModelPathsYamlHelper
{
    /// <summary>
    /// 扫描模型根目录的一级子目录，生成 extra_model_paths.yaml 文件内容。
    /// </summary>
    /// <param name="basePath">模型根目录。</param>
    /// <returns>符合 ComfyUI 格式的 YAML 文本。</returns>
    public static string GenerateYamlContent(string basePath)
    {
        var normalizedPath = basePath.Replace('\\', '/');
        if (!normalizedPath.EndsWith('/'))
        {
            normalizedPath += '/';
        }

        var directoryNames = Directory.EnumerateDirectories(basePath, "*", SearchOption.TopDirectoryOnly)
            .Select(dir => Path.GetFileName(dir))
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var yamlLines = new List<string>
        {
            "# Auto-generated by ComfyShell",
            "# 扩展模型路径配置",
            "",
            "comfyui_extra:",
            $"    base_path: {normalizedPath}"
        };

        foreach (var name in directoryNames)
        {
            yamlLines.Add($"    {name}: {name}/");
        }

        yamlLines.Add(string.Empty);
        return string.Join(Environment.NewLine, yamlLines);
    }
}
